# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ["localhost:9093"] # alertmanager machine ip

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/opt/prometheus-{{ prometheus_version  }}/proxy_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'machine_heart'
    metrics_path: /probe
    params:
      module: [ssh_banner]
    file_sd_configs:
    - files: ['/opt/prometheus-{{ prometheus_version  }}/machine.json']
      refresh_interval: 5m
    relabel_configs:
    - source_labels: [__address__]
      regex: (.*)
      replacement: ${1}
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: localhost:9115

  - job_name: 'machine_report'
    metrics_path: /probe
    scrape_interval: 5s
    scrape_timeout:  5s
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://10.31.54.65:9999/monitor/monitorMachine
    file_sd_configs:
    - files: ['/opt/machine.json']
      refresh_interval: 5m
    relabel_configs:
    - source_labels: [__address__]
      regex: (.*)
      replacement: ${1}
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - source_labels: [__param_target]
      regex: (.*)
      replacement: http://10.31.54.65:9999/monitor/monitorMachine?target=${1}
      target_label: __param_target
    - target_label: __address__
      replacement: localhost:9115 # blackbox machine ip
