- name: Temporary Close SELinux
  selinux:
    policy: targeted
    state: disabled
- name: Permanent Close SELinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
- name: Disable swap
  command: swapoff -a
- name: Add kubernetes.repo
  template: src=kubernetes.repo dest=/etc/yum.repos.d/
- name: Install kubelet kubeadm kubectl
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: kubernetes
  with_items:
    - kubelet
    - kubeadm
    - kubectl
