- hosts: all
  remote_user: root
  vars:
    registry_server: "https://index.docker.io/v1" # the docker hub registry
  tasks:
  - name: Add Docker Registry
    shell: echo {{ registry_password }} | docker login --username {{ registry_username }} --password-stdin {{ registry_server }}
