- name: Add kubernetes.repo
  template: src=kubernetes.repo dest=/etc/yum.repos.d/
- name: Install kubelet kubeadm kubectl
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: kubernetes
  with_items:
    - kubelet
    - kubeadm
    - kubectl
- name: Copy images scripts
  template: src=pull_images.sh dest=/opt
- name: Pull k8s relevant images
  shell: sh /opt/pull_images.sh
