- name: Copy images scripts
  template: src=pull_images.sh dest=/opt
- name: Pull k8s relevant images
  shell: sh /opt/pull_images.sh
- name: Initial master
  shell: kubeadm init --kubernetes-version=v1.11.2 --pod-network-cidr=10.244.0.0/16
- name: Create kube admin.conf directory
  file: dest=/root/.kube state=directory
- name: Copy admin.conf
  shell: cp -i /etc/kubernetes/admin.conf ~/.kube/config
- name: Add kubeconfig environment variables
  lineinfile:
    path: /etc/profile
    line: export KUBECONFIG=/etc/kubernetes/admin.conf
  notify:
  - Source profile
- name: Add-on flannel plug
  import_tasks: flannel/main.yml
