- name: Add kubernetes.repo
  template: src=kubernetes.repo dest=/etc/yum.repos.d/
- name: Temporary Close SELinux
  selinux:
    policy: targeted
    state: disabled
- name: Permanent Close SELinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
- name: Disable swap
  command: swapoff -a
- name: Install kubelet
  yum:
    name: kubelet
    state: installed
    enablerepo: kubernetes
- name: Install kubeadm
  yum:
    name: kubeadm
    state: installed
    enablerepo: kubernetes
- name: Install kubectl
  yum:
    name: kubectl
    state: installed
    enablerepo: kubernetes
- name: Stared kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
