- name: Install kubernetes
  hosts: all
  remote_user: root
  roles:
    - {role: "docker", tags: "docker"}
    - {role: "common", tags: "common"}
    - {role: "master", tags: "master"}
    - {role: "flannel", tags: "flannel"}
