- hosts: all
  remote_user: root
  tasks:
  - name: Install relevant utils
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - epel-release
    - python-pip
  - name: Install shadowsocks
    pip:
      name: "{{ item }}"
      state: present
      extra_args: --upgrade 
    with_items:
    - pip
    - shadowsocks
  - name: Copy shadowsocks.json
    template: src=templates/shadowsocks.json dest=/etc
    notify:
    - Restart shadowsocks
  - name: Init shadowsocks.service
    template: src=templates/shadowsocks.service dest=/usr/lib/systemd/system
    notify:
    - Restart shadowsocks
  - name: Install privoxy
    yum:
      name: privoxy
      state: present
  - name: Config privoxy config
    lineinfile:
      path: /etc/privoxy/config
      line: "forward-socks5t / 127.0.0.1:1080 ."
    notify:
    - Restart privoxy
  - name: Config environment
    lineinfile:
      dest: /etc/profile
      line: "{{ item }}"
    with_items:
    - export http_proxy=http://127.0.0.1:8118
    - export https_proxy=http://127.0.0.1:8118 
  - name: Source /etc/profile
    shell: source /etc/profile
  handlers:
  - name: Restart shadowsocks
    systemd:
      name: shadowsocks
      state: restarted
      daemon_reload: yes
  - name: Restart privoxy
    systemd:
      name: privoxy
      state: restarted
      daemon_reload: yes
